submission/edit/forms/biological_activity.py
"""Biological activity for compounds"""

from wtforms import (
    Form,
    StringField,
    BooleanField,
    FloatField,
    SelectField,
    FieldList,
    FormField,
    SubmitField,
    validators,
)
from markupsafe import Markup

from submission.utils.custom_widgets import (
    FieldListAddBtn,
    SelectDefault,
    SubmitIndicator,
    TextInputWithSuggestions,
)
from submission.utils.custom_fields import ReferenceField
from submission.utils.custom_validators import RequiredIf, ValidateCitations


class AssayForm(Form):
    class ConcentrationForm(Form):
        concentration = FloatField(
            "Concentration",
            description=Markup(
                "If activity was observed, state the lowest effective concentration.<br>"
                "If activity was <u>not</u> observed, state the highest tested concentration."
            ),
            validators=[validators.Optional()],
        )
        # TODO: expand units
        concentration_unit = SelectField(
            "Unit",
            widget=SelectDefault(),
            choices=[
                "mg/mL",
                "µg/mL",
                "ng/mL",
                "pg/mL",
                "milimolar",
                "micromolar",
                "nanomolar",
                "picomolar",
            ],
            validate_choice=False,
            validators=[
                RequiredIf(
                    "concentration",
                    message="This field is required when concentration is filled.",
                )
            ],
        )

    # TODO: show hierarchy, e.g. ionophore has deeper level: chalcophore etc.
    target = SelectField(
        "Property *",
        widget=SelectDefault(),
        choices={
            "chemical properties": [
                "denitrificative",
                "emulsifier",
                "flavor",
                "fluorescent",
                "surfactant",
                "ionophore",
                "chalcophore",
                "lanthanophore",
                "siderophore",
                "zincophore",
                "odorous metabolite",
                "pigment",
                "radical scavenging",
            ],
            "therapeutic properties": [
                "antibacterial",
                "anti-Gram-negative",
                "anti-Gram-positive",
                "anticancer",
                "antineoplastic",
                "antitumor",
                "antifungal",
                "antiinflammatory",
                "antioomycete",
                "antiparasidal",
                "anthelmintic",
                "antiplasmodial",
                "antimalarial",
                "antiprotozoal",
                "anticoccidial",
                "antiproliferative",
                "antitubulin",
                "antiviral",
                "herbicidal",
                "antialgal",
                "immunomodulatory",
                "immunosuppressive",
                "insecticidal",
                "neuroprotective",
                "sodium channel blocking",
                "toxic",
                "cytotoxic",
                "cytostatic",
                "dermatotoxic",
                "DNA-interfering",
                "enterotoxic",
                "hemolytic",
                "hepatotoxic",
                "irritant",
                "neurotoxic",
                "phytotoxic",
                "tumor promoter",
                "vesicant",
            ],
            "cellular processes": [
                "adhesion",
                "biofilm",
                "cell differentiation",
                "cell envelope",
                "cell wall",
                "cell protectant",
                "cyst formation",
                "exopolysaccharide",
                "extracellular capsule",
                "predation",
                "regulatory",
                "inducer",
                "inhibitor",
                "proteasome inhibition",
                "signalling",
                "plant-defense signalling",
                "morphogen",
                "stress response",
                "antioxidant",
                "carbon storage",
                "cold stress",
                "iron reducing",
                "nitrogen reduction",
                "osmolytic",
                "UV protective",
                "swarming motility",
                "virulence factor",
            ],
            "other": ["other"],
        },
        validate_choice=False,
        validators=[validators.InputRequired()],
    )
    references = ReferenceField(
        "Citation(s) *",
        description="Comma separated list of references highlighted this activity. If references show different concentration, add them separately.",
        widget=TextInputWithSuggestions(post_url="/edit/get_db_references"),
        validators=[validators.InputRequired(), ValidateCitations()],
    )
    obeserved = BooleanField(
        "Observed",
        description=Markup(
            "Untick if this activity was tested for <u>but not observed</u>"
        ),
        default="checked",
    )
    concentration = FormField(ConcentrationForm, label="Concentration (Optional)")


class BioActivityForm(Form):
    compound = StringField("Compound *", validators=[validators.InputRequired()])
    assays = FieldList(
        FormField(AssayForm),
        min_entries=0,
        widget=FieldListAddBtn(
            label="Add assay",
        ),
    )


class BioActivityMultiple(Form):
    activities = FieldList(
        FormField(BioActivityForm),
        widget=FieldListAddBtn(
            label="Add compound",
        ),
    )
    submit = SubmitField("Submit", widget=SubmitIndicator())

submission/edit/forms/edit_select.py
from wtforms import Form, SubmitField


class EditSelectForm(Form):
    minimal = SubmitField("Minimal Entry")
    structure = SubmitField("Structure")
    activity = SubmitField("Biological activity")
    biosynth = SubmitField("Class-specific and biosynthesis information")
    tailoring = SubmitField("Tailoring reaction information")
    annotation = SubmitField("Gene annotation")

submission/edit/forms/form_collection.py
from submission.edit.forms.structure import StructureMultiple
from submission.edit.forms.min_entry import MinEntryForm
from submission.edit.forms.biological_activity import BioActivityMultiple
from submission.edit.forms.biosynthesis import (
    NRPSForm,
    PKSForm,
    RibosomalForm,
    SaccharideForm,
    TerpeneForm,
    OtherForm,
    OperonMultipleForm,
)
from submission.edit.forms.biosynthesis_paths import PathMultipleForm
from submission.edit.forms.biosynthesis_modules import ModulesForm
from submission.edit.forms.tailoring import TailoringMultipleForm
from submission.edit.forms.gene_annotation import GeneAnnotationForm


class FormCollection:
    minimal = MinEntryForm
    structure = StructureMultiple
    bioact = BioActivityMultiple

    # Biosynthesis classes
    NRPS = NRPSForm
    PKS = PKSForm
    Ribosomal = RibosomalForm
    Saccharide = SaccharideForm
    Terpene = TerpeneForm
    Other = OtherForm

    operons = OperonMultipleForm
    paths = PathMultipleForm
    modules = ModulesForm

    tailoring = TailoringMultipleForm
    annotation = GeneAnnotationForm

submission/edit/__init__.py
from flask import Blueprint

bp_edit = Blueprint("edit", __file__, url_prefix="/edit")

from submission.edit import views

submission/edit/views.py
import re
import csv
from pathlib import Path
from typing import Union

from sqlalchemy import select, or_
from flask import (
    abort,
    render_template,
    render_template_string,
    request,
    redirect,
    url_for,
    flash,
)
from flask_login import current_user, login_required
from werkzeug.datastructures import MultiDict
from werkzeug.wrappers import response
from wtforms.widgets import html_params
from markupsafe import Markup

from submission.extensions import db
from submission.edit import bp_edit
from submission.edit.forms.form_collection import FormCollection
from submission.edit.forms.edit_select import EditSelectForm
from submission.utils import Storage, draw_smiles_svg, draw_smarts_svg
from submission.utils.custom_validators import is_valid_bgc_id
from submission.utils.custom_errors import ReferenceNotFound
from submission.models import Entry, NPAtlas, Substrate


@bp_edit.route("/<bgc_id>", methods=["GET", "POST"])
@login_required
def edit_bgc(bgc_id: str) -> Union[str, response.Response]:
    """Overview page with navigation to forms for entry sections

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str | Response: rendered overview template or redirect section form
    """

    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    form = EditSelectForm(request.form)
    if request.method == "POST":
        for option, chosen in form.data.items():
            if chosen:
                return redirect(url_for(f"edit.edit_{option}", bgc_id=bgc_id))
    return render_template("edit/edit.html", form=form, bgc_id=bgc_id)


@bp_edit.route("/<bgc_id>/minimal", methods=["GET", "POST"])
@login_required
def edit_minimal(bgc_id: str) -> Union[str, response.Response]:
    """Form to enter minimal entry information

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str | Response: rendered form template or redirect to edit_bgc overview
    """
    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    # try to fill data from existing entry
    if not request.form:
        data: MultiDict = MultiDict(Storage.read_data(bgc_id).get("Minimal"))
        form = FormCollection.minimal(data)
        reviewed = data.get("reviewed")
    else:
        form = FormCollection.minimal(request.form)
        # do not prefill reviewed checkbox on failed post
        reviewed = False

    if request.method == "POST" and form.validate():
        try:
            Entry.save_minimal(bgc_id=bgc_id, data=form.data)
            Storage.save_data(bgc_id, "Minimal", request.form, current_user)
            flash("Submitted minimal entry!")
            return redirect(url_for("edit.edit_bgc", bgc_id=bgc_id))
        except ReferenceNotFound as e:
            flash(str(e), "error")
    return render_template(
        "edit/min_entry.html",
        form=form,
        bgc_id=bgc_id,
        is_reviewer=current_user.has_role("reviewer"),
        reviewed=reviewed,
    )


@bp_edit.route("/<bgc_id>/structure", methods=["GET", "POST"])
@login_required
def edit_structure(bgc_id: str) -> Union[str, response.Response]:
    """Form to enter structure information

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str | Response: rendered form template or redirect to edit_bgc overview
    """
    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    if not request.form:
        data: MultiDict = MultiDict(Storage.read_data(bgc_id).get("Structure"))
        form = FormCollection.structure(data)
        reviewed = data.get("reviewed")
    else:
        form = FormCollection.structure(request.form)
        reviewed = False

    if request.method == "POST" and form.validate():
        try:
            Entry.save_structure(bgc_id=bgc_id, data=form.data)
            Storage.save_data(bgc_id, "Structure", request.form, current_user)
            flash("Submitted structure information!")
            return redirect(url_for("edit.edit_bgc", bgc_id=bgc_id))
        except ReferenceNotFound as e:
            flash(str(e), "error")

    # on GET query db for any products already present
    else:
        # if one (or more) is present prefill
        try:
            products = next(
                csv.reader(
                    [
                        MultiDict(Storage.read_data(bgc_id).get("Minimal")).get(
                            "products"
                        )
                    ],
                    skipinitialspace=True,
                )
            )
        except:
            products = []

        for product in products:
            if product not in [struct.data.get("name") for struct in form.structures]:
                form.structures.append_entry(data={"name": product})
    return render_template(
        "edit/structure.html",
        form=form,
        bgc_id=bgc_id,
        is_reviewer=current_user.has_role("reviewer"),
        reviewed=reviewed,
    )


@bp_edit.route("/render_smiles", methods=["POST"])
@login_required
def render_smiles() -> Union[str, response.Response]:
    origin = request.headers["Hx-Trigger-Name"]
    smiles_string = request.form.get(origin)

    if smiles_string is None or not (smiles := smiles_string.strip()):
        return ""

    return draw_smiles_svg(smiles)


@bp_edit.route("/<bgc_id>/bioact", methods=["GET", "POST"])
@login_required
def edit_activity(bgc_id: str) -> Union[str, response.Response]:
    """Form to enter biological activity information

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str | Response: rendered form templare or redirect to edit_bgc overview
    """
    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    if not request.form:
        data: MultiDict = MultiDict(Storage.read_data(bgc_id).get("Bio_activity"))
        form = FormCollection.bioact(data)
        reviewed = data.get("reviewed")
    else:
        form = FormCollection.bioact(request.form)
        reviewed = False
    if request.method == "POST" and form.validate():
        try:
            Entry.save_activity(bgc_id=bgc_id, data=form.data)
            Storage.save_data(bgc_id, "Bio_activity", request.form, current_user)
            flash("Submitted activity information!")
            return redirect(url_for("edit.edit_bgc", bgc_id=bgc_id))
        except ReferenceNotFound as e:
            flash(str(e), "error")
    else:
        # prefill compounds
        try:
            products = next(
                csv.reader(
                    [
                        MultiDict(Storage.read_data(bgc_id).get("Minimal")).get(
                            "products"
                        )
                    ],
                    skipinitialspace=True,
                )
            )
        except:
            products = []

        for product in products:
            if product not in [act.data.get("compound") for act in form.activities]:
                form.activities.append_entry(data={"compound": product})
    return render_template(
        "edit/biological_activity.html",
        bgc_id=bgc_id,
        form=form,
        is_reviewer=current_user.has_role("reviewer"),
        reviewed=reviewed,
    )


@bp_edit.route("/<bgc_id>/biosynth", methods=["GET", "POST"])
@login_required
def edit_biosynth(bgc_id: str) -> str:
    """Selection overview page for class-specific biosynthesis forms

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str: rendered template
    """
    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    return render_template("edit/biosynthesis.html", bgc_id=bgc_id)


@bp_edit.route("/class_buttons/<bgc_id>", methods=["POST"])
@login_required
def class_buttons(bgc_id: str) -> str:
    """Obtain buttons linking to relevant biosynthetic classes for this BGC

    Args:
        bgc_id (str): BGC identifier

    Returns:
        str: html buttons linking to class-specific form templates
    """

    # grab classes for current bgc_id
    classes = MultiDict(Storage.read_data(bgc_id).get("Minimal")).getlist("b_class")

    if not classes:
        classes = ["NRPS", "PKS", "Ribosomal", "Saccharide", "Terpene", "Other"]
    class_btns = ""
    for cls in classes:
        class_btns += f"<a class='btn btn-light' style='margin: 5px' role='button' href='/edit/{bgc_id}/biosynth/{cls}'>{cls}</a>"
    return class_btns


@bp_edit.route("/<bgc_id>/biosynth/<b_class>", methods=["GET", "POST"])
@login_required
def edit_biosynth_class(bgc_id: str, b_class: str) -> Union[str, response.Response]:
    """Form to enter class-specific biosynthesis information

    Args:
        bgc_id (str): BGC identifier
        b_class (str): Biosynthetic class

    Returns:
        str | Response: rendered template or redirect to edit_bgc overview
    """
    if not is_valid_bgc_id(bgc_id):
        return abort(403, "Invalid existing entry!")

    if not request.form:
        data: MultiDict = MultiDict(
            Storage.read_data(bgc_id).get(f"BioSynth_{b_class}")
        )
        form = getattr(FormCollection, b_class)(data)
        reviewed = data.get("reviewed")
    else:
        form = getattr(FormCollection, b_class)(request.form)
        reviewed = False

    if request.method == "POST" and form.validate():
        try:
            Entry.save_biosynth(bgc_id=bgc_id, b_class=b_class, data=form.data)
            Storage.save_data(bgc_id, f"BioSynth_{b_class}", request.form, current_user)
            flash(f"Submitted {b_class} biosynthesis information!")
            return redirect(url_for("edit.edit_biosynth", bgc_id=bgc_id))
        except ReferenceNotFound as e:
            flash(str(e), "error")

    return render_template(
        "edit/biosynth_class_specific.html",
        form=form,
        b_class=b_class,
        bgc_id=bgc_id,
        is_reviewer=current_user.has_role("reviewer"),
        reviewed=reviewed,
    )

submission/templates/edit/WIP.html
{% extends 'base.html' %}

{% block body %}
<div>
    <h2>Work in Progress!</h2>
    <button class="btn-primary" onclick="history.back()">Go Back</button>
</div>
{% endblock %}

submission/templates/edit/annotation.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>

{% endblock %}

{% block body %}
<div class="form-wrapper">

    <h4>Enter gene annotation information</h4>
    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}

</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button id="back-btn" class="btn btn-outline-secondary">Back
            to
            overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biological_activity.html
{% extends 'base.html' %}

{% import 'macros.html' as macros%}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}


<div class="form-wrapper">
    <h4>Enter biological activities</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button id="back-btn" class="btn btn-outline-secondary">Back
            to
            overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biosynth_class_specific.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h4>Enter {{ b_class }} Class-specific biosynthesis information</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_biosynth', bgc_id=bgc_id) }}"><button id="back-btn"
            class="btn btn-outline-secondary">Back to
            Biosynthesis overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biosynth_modules.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h4>Enter biosynthesis module information</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_biosynth', bgc_id=bgc_id) }}"><button id="back-btn"
            class="btn btn-outline-secondary">Back to
            Biosynthesis overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biosynth_operons.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h4>Enter operon information</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_biosynth', bgc_id=bgc_id) }}"><button id="back-btn"
            class="btn btn-outline-secondary">Back to
            Biosynthesis overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biosynth_paths.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h4>Enter biosynthesis path information</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_biosynth', bgc_id=bgc_id) }}"><button id="back-btn"
            class="btn btn-outline-secondary">Back to
            Biosynthesis overview</button></a>
</div>
{% endblock %}

submission/templates/edit/biosynthesis.html
{% extends 'base.html' %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h3>Biosynthesis Overview</h3>
    <div class="container" style="margin: 15px 3px 15px 3px">
        <h4>Select relevant biosynthetic class</h4>

        <div class="tab-container" hx-post="{{ url_for('edit.class_buttons', bgc_id=bgc_id) }}" hx-trigger="load"
            hx-swap="innerHTML">
        </div>
    </div>
    <div class="container" style="margin: 15px 3px 15px 3px">
        <h4>Select to enter operons</h4>

        <div><a class="btn btn-light" href=" {{ url_for('edit.edit_biosynth_operons', bgc_id=bgc_id) }}">Operons</a>
        </div>
    </div>
    <div class="container" style="margin: 15px 3px 15px 3px">
        <h4>Select to enter biosynthetic paths</h4>

        <div><a class="btn btn-light" href=" {{ url_for('edit.edit_biosynth_paths', bgc_id=bgc_id) }}">Paths</a></div>
    </div>
    <div class="container" style="margin: 15px 3px 15px 3px">
        <h4>Select to enter biosynthetic module information</h4>

        <div><a class="btn btn-light" href=" {{ url_for('edit.edit_biosynth_modules', bgc_id=bgc_id) }}">Modules</a>
        </div>
    </div>
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button class="btn btn-outline-secondary">Back to
            overview</button></a>
</div>
{% endblock %}

submission/templates/edit/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
{%- if field.type == 'BooleanField' %}
<div class="form-check mb-3">
    {{ field(class='form-check-input') }}
    {{ field.label(class='form-check-label') }}
</div>
{%- elif field.type == 'RadioField' %}
{{ field.label(class='form-label') }}
{%- for item in field %}
<div class="form-check{% if loop.last %} mb-3{% endif %}">
    {{ item(class='form-check-input') }}
    {{ item.label(class='form-check-label') }}
</div>
{%- endfor %}
{%- elif field.type == 'SelectField' %}
{{ field.label(class='form-label') }}
{{ field(class='form-select mb-3') }}
{%- elif field.type == 'TextAreaField' %}
<div class="mb-3">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
    {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
    {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
</div>
{%- elif field.type == 'SubmitField' %}
{{ field(class='btn btn-primary mb-3') }}
{%- elif field.type == 'FieldList' %}
<div class="mb-3">
    <!-- {{ field.label(class='form-label') }} -->
    {% for subfield in field %}
    {{ form_field(subfield) }}
    {% endfor %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
</div>
{% elif field.type == 'FormField' %}
<div class="mb-2">
    {{ field.label(class='form-label') }}
    {% for subfield in field %}
    {{ form_field(subfield) }}
    {% endfor %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
</div>
{%- else %}
<div class="mb-2">
    {{ field.label(class='form-label') }}
    {% if autofocus %}
    {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
    {% else %}
    {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
    {% endif %}
    {%- for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
</div>
{%- endif %}
{% endmacro %}

{% macro quick_form(form, action="", method="post", id="", novalidate=False) %}
<form novalidate {%- if action !=None %} action="{{ action }}" {% endif -%} {%- if method %} method="{{ method }}" {%
    endif %} {%- if id %} id="{{ id }}" {% endif -%} {%- if novalidate %} novalidate{% endif -%}>
    {%- for field, errors in form.errors.items() %}
    {%- if form[field].widget.input_type == 'hidden' %}
    {%- for error in errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {%- endfor %}
    {%- endif %}
    {%- endfor %}

    {% set ns = namespace(first_field=true) %}
    {%- for field in form %}
    {% if field.widget.input_type != 'hidden' -%}
    {{ form_field(field, ns.first_field) }}
    {% set ns.first_field = false %}
    {%- endif %}
    {%- endfor %}
</form>
{% endmacro %}




{% macro div_form(form) %}
<form method="post" class="container">
    {% for field in form %}
    <div>
        {% if field.type != "SubmitField" and field.type != "HiddenField" %}
        {{field.label}}
        {{field}}
        {% if field.errors %}
        {% for error in field.errors %}
        <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}
        {% endif %}
    </div>

    {% elif field.type == 'HiddenField' %}
    {{field}}
    {% endif %}
    {% endfor %}
    {% for field in form %}
    {% if field.type == "SubmitField" %}
    {{field}}
    {% endif %}
    {% endfor %}
</form>
{% endmacro %}

submission/templates/edit/edit.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}
<div class="form-wrapper">
    <h4>What would you like to edit?</h4>
    {{ macros.simple_divform(form) }}
</div>
<div class="container">
    <a href="{{ url_for('main.index') }}"><button class="btn btn-outline-secondary">Back to entry selection</button></a>
</div>
{% endblock %}

submission/templates/edit/forms_basic.html
{% extends 'base.html' %}

{% import 'bootstrap_wtf.html' as wtf %}

{% block body %}
<div>
    <h2>Editing {{ bgc_id }}</h2>
</div>
<h4>Enter {{ b_class }} Class-specific biosynthesis information</h4>
<!-- <form method="post" class="container">
    <fieldset>
        <table>
            <tbody>
                {% for field in form %}
                {% if field.type != "SubmitField" and field.type != "HiddenField" %}
                <tr>
                    <th>
                        {{field.label}}
                    </th>
                    <td>
                        {{field}}

                    </td>
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <li class="invalid-feedback">{{ error }}</li>
                    {% endfor %}
                    {% endif %}
                </tr>
                {% elif field.type == 'HiddenField' %}
                {{field}}
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </fieldset>
    {% for field in form %}
    {% if field.type == "SubmitField" %}
    {{field}}
    {% endif %}
    {% endfor %}
</form> -->

{{wtf.simple_form(form)}}

<div class="container">
    <a href="{{ url_for('edit_biosynth', bgc_id=bgc_id) }}"><button class="btn-primary">Back to Class
            selection</button></a>
</div>
{% endblock %}

submission/templates/edit/min_entry.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>

{% endblock %}

{% block body %}
<div class="form-wrapper">

    <h4>Enter minimal information</h4>
    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}

</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button id="back-btn" class="btn btn-outline-secondary">Back
            to
            overview</button></a>
</div>
{% endblock %}

submission/templates/edit/structure.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}
<div class="form-wrapper">
    <h4>Enter compound information</h4>
    {{macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed)}}

</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button id="back-btn" class="btn btn-outline-secondary">Back
            to
            overview</button></a>
</div>
{% endblock %}

submission/templates/edit/tailoring.html
{% extends 'base.html' %}

{% import 'macros.html' as macros %}

{% block header %}
<h2 class="edit-header">Editing {{ bgc_id }}</h2>
{% endblock %}

{% block body %}

<div class="form-wrapper">
    <h4>Enter tailoring information</h4>

    {{ macros.simple_divform(form, is_reviewer=is_reviewer, reviewed=reviewed) }}
</div>
<div class="container">
    <a href="{{ url_for('edit.edit_bgc', bgc_id=bgc_id) }}"><button id="back-btn" class="btn btn-outline-secondary">Back
            to
            overview</button></a>
</div>
{% endblock %}